### ISSUE TITLE
"コンテンツ > Linuxでのbuild方法" を書く

### ISSUE THREAD

**Issue by kozo2** [emacs-jp/emacs-jp.github.com#112]
ここに **emacs25** のビルド方法を書く
![screen shot 2016-05-25 at 10 13 13 am](https://cloud.githubusercontent.com/assets/12192/15525024/58569582-2261-11e6-9292-78e402b09752.png)

**Comment by kozo2** [comment]
どっかにすでに**Linuxでのbuild方法**がまとめられてるとこがあったら教えてください。
パクるので

**Comment by lurdan** [comment]
このあたり？
https://www.emacswiki.org/emacs/BuildingEmacs
http://ergoemacs.org/emacs/building_emacs_on_linux.html
http://myemacs.readthedocs.io/ja/latest/build.html

**Comment by kozo2** [comment]
fa778c61d0c9217eda4a1a63350c80b7afd3a4cb
でひとまずclose
