### ISSUE TITLE
elscreenのメンテナンス(及びそのプラグイン)

### ISSUE THREAD

**Issue by syohex** [emacs-jp/emacs-jp.github.com#13]
github版がいくつかある
- [https://github.com/shosti/elscreen](https://github.com/shosti/elscreen) MELPA版
- [https://github.com/knu/elscreen](https://github.com/knu/elscreen)

プラグインについては、MELPA版 elscreenを使うと動作しないものが
見られる(elscreen-wlは確認)
- [https://github.com/syohex/emacs-elscreen-wl](https://github.com/syohex/emacs-elscreen-wl) 拙作の fork版

意見求む。意見が出てきたらプラグインは別 issueとする。

**Comment by znz** [comment]
いつのまにか melpa の elscreen は knuさん版に変わっていて問題なく使えているようです。
