### ISSUE TITLE
lexical-binding in tips/startup-optimization

### ISSUE THREAD

**Issue by tkita** [emacs-jp/emacs-jp.github.com#161]
tips/startup-optimization の lexical-binding で質問があります。
最初の動的束縛のコード例において `(defvar fn ...)` の中の `lambda` ではシンボル a を全く参照していません。
このような `lambda` でも `(let ((a 2)) ...)` の評価結果は本当に 5 になるのでしょうか？

```diff
- (lambda (x) (+ x 1))))
+ (lambda (x) (+ x a))))
```
上記 diff とするなら `(let ((a 2)) ...)` の評価結果は 5 になりそうですが、
そうすると `(funcall fn 3)` の評価時にシンボル a は未束縛となってしまいます（評価結果 4 は得られません）。

**Comment by conao3** [comment]
(著者に通知が行ってないと思うのでメンションします > @zk-phi )

**Comment by tkita** [comment]
文章では伝わらないかもしれませんので、手元での再現結果をお伝えしておきます。動的束縛である GNU Emacs 24 です。

```
(version)
"GNU Emacs 24.3.1 (i686-pc-linux-gnu, GTK+ Version 2.16.6) of 2020-02-22 on fedora"

(defvar fn
  (let ((a 1))
    (lambda (x) (+ x 1))))
fn

(funcall fn 3)
4

(let ((a 2))
  (funcall fn 3))
4 ;; 5 ではない
```

5 にしようとしてみると、
```
(defvar fn
  (let ((a 1))
    (lambda (x) (+ x a))))
fn

(let ((a 2))
  (funcall fn 3))
5

(funcall fn 3)
Lisp error: void-variable a
```
@zk-phi さま、検証よろしくお願いいたします。

**Comment by zk-phi** [comment]
``` diff
- (lambda (x) (+ x 1))))
+ (lambda (x) (+ x a))))
```

これはまさしくです、書き間違いだったのでありがとうございます…！mm

静的・動的束縛の仕様については、こんな感じで束縛戦略だけが違う２つのファイルを用意して、

https://gist.github.com/zk-phi/08b82e84f7b4705f454aed3d70c2b714
https://gist.github.com/zk-phi/70771eccf18c6346bfc8b6c19feb30bb

ロードしてみると

```emacs-lisp
(load "~/Documents/dotfiles/test-lexical.el")
(load "~/Documents/dotfiles/test-dynamic.el")
```

以下のように `4`, `5` が得られます。

<img width="611" alt="スクリーンショット 2020-09-09 11 03 52" src="https://user-images.githubusercontent.com/3530521/92545900-2cd94080-f28c-11ea-8c56-b6ab52226054.png">

ひょっとすると eval-last-sexp などで評価すると変わるのかもですかね…？（一律 lexical-binding になったのは 27 からっぽいですが。。）

**Comment by zk-phi** [comment]
あっすみません意図を理解しました、確かに動的束縛の場合に a を let せずに funcall すると void-variable になりますね！

ありがとうございます、こちらも修正しますmm

**Comment by tkita** [comment]
対応ありがとうございます！
close します。
