### ISSUE TITLE
tips/startup-optimization: use append() instead of concat()

### ISSUE THREAD

**Issue by tkita** [emacs-jp/emacs-jp.github.com#164]
「コンスセルを理解する」の箇所で、次のように記述されています。

    たとえば二つのリストを連結したいとき、 Emacs Lisp では concat または nconc を使うことができますが、
    それぞれ次のような違いがあります。
    (concat A B) … A, B の要素をすべて並べた新しいリストを作る

Emacs Lisp では 正しくは append でしょうか。

```lisp
(version)
;;; "GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-12"

(concat '(a b c) '(d e f))
;;; Lisp error: wrong-type-argument characterp a

(append '(a b c) '(d e f))
;;; (a b c d e f)
```

@zk-phi さま、検証よろしくお願いいたします。

**Comment by zk-phi** [comment]
おっしゃる通りですmm
サンプルコードちゃんと全部テストしてから投稿しないとダメですね。。修正 PR 作りました！

**Comment by tkita** [comment]
ありがとうございます！
close します。
