### ISSUE TITLE
Emacsにシェルの環境変数を取り込む

### ISSUE THREAD

**Issue by zonuexe** [emacs-jp/emacs-jp.github.com#18]
**[purcell/exec-path-from-shell: Make Emacs use the $PATH set up by the user's shell](https://github.com/purcell/exec-path-from-shell)を使いましょう。**

* MELPA: [exec-path-from-shell](https://melpa.org/#/exec-path-from-shell)
* [EmacsでPATHの設定が引き継がれない問題をエレガントに解決する - Qiita](https://qiita.com/catatsuy/items/3dda714f4c60c435bb25)

-----

~~「こんな拡張書いたけど、見て欲しい」な宣伝なのですが ヾ(〃＞＜)ﾉﾞ☆~~

- リポジトリ
  - ~~[zonuexe/shellenv-el · GitHub](https://github.com/zonuexe/shellenv-el)~~
- 説明書
  - [Emacsに環境変数を取り込む… の次。(with 初めてのelisp) - Qiita](http://qiita.com/items/bdc979a7b93ea8f76bd3)
  - [Emacsに環境変数を取り込む… をもっと。 - Qiita](http://qiita.com/items/51a2b869774f93f0d7cb)

他の方は Emacs で、たとへば `PATH` 環境変数や `exec-path` などをどう管理してるのか、も気になります。

**Comment by kawabata** [comment]
NTEmacs で、かつ shell-file-name が、msys/cygwin の "bash.exe" または "zsh.exe" の場合は、
":"で split したあと、cygpath -amp で変換しなければうまくいかなかったような。
