### ISSUE TITLE
Emacs for Windowsをインストールする際にopensshがインストールできない

### ISSUE THREAD

**Issue by osam023** [emacs-jp/emacs-jp.github.com#189]
PowerShellで下記のコマンドを実行するとopensshのインストールが失敗します。
```scoop install ag direnv fzf git global go nodejs-lts openssh ripgrep gow fd gpg```

**Comment by syohex** [comment]
再現することは確認できました. 依存パッケージがリポジトリにないっぽい.

最近の Windows 10だと OpenSSHは標準で入っているので一旦 opensshは無視して進んでいただければよいと思います

**Comment by osam023** [comment]
opensshを外して実行していますが問題なく動いてそうです。
ありがとうございました。
