### ISSUE TITLE
`rust-analyzer` ダウンロード URL について

### ISSUE THREAD

**Issue by toyboot4e** [emacs-jp/emacs-jp.github.com#197]
@KeenS
[Rustプログラミングのための環境構築](https://emacs-jp.github.io/env/rust) に沿って `rust-analyzer` をダウンロードしました:

```sh
$ curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-mac \
    -o ~/.local/bin/rust-analyzer
```

その後、エディタで不可解なエラーが出たのですが、 `rust-analyzer` がテキストファイルだったのが問題でした:

```sh
$ cat ~/.local/bin/rust-analyzer
Not Found
```

[最近](https://github.com/rust-analyzer/rust-analyzer/releases) はダウンロード URL が変わっているようです。
お時間の空いた際に、更新していただけたらと思います 🙇‍♂️

---

初めて action を使用しました。詳しい記事をありがとうございます！

**Comment by syohex** [comment]
https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-05-17

これまでは非圧縮のバイナリそのものが提供されていたけど, 以降は gzip圧縮したものしかないということですかね. なんで URLを `.gz` の URLにして展開コマンドを追加する形になりますでしょうか.
