### ISSUE TITLE
herokuに代わる slack招待 URLアプリ or 手段

### ISSUE THREAD

**Issue by syohex** [emacs-jp/emacs-jp.github.com#210]
Herokuの無料プランが終了するため, 代替手段の提供が必要である.
標準の招待 URLは一定期間で失効してしまうため利用する場合定期的な更新が必要. なので slack APIを利用するものが好ましいと考える

案
- 別のとこかに同様のアプリをデプロイする
- 手動で毎月更新する. github actionsの cron等を使い更新忘れは置きづらくする

**Comment by syohex** [comment]
参考記事 Herokuの代替サービス30選、使ってみた参考記事リンク付き
- https://qiita.com/rana_kualu/items/f7fc4916b7dc9797839e

**Comment by conao3** [comment]
いつごろか、無期限のURLが作れるようになっているので、それも案にはなるかなと思います。
[Slackで期限なし(無期限)の招待リンクを作成する方法　2021](https://mocotan.hatenablog.com/entry/2021/11/23/071657)

ただし、リンクされているSlackのヘルプを見ると
https://slack.com/intl/ja-jp/help/articles/201330256-%E3%83%AF%E3%83%BC%E3%82%AF%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9%E3%81%AB%E6%96%B0%E8%A6%8F%E3%83%A1%E3%83%B3%E3%83%90%E3%83%BC%E3%82%92%E6%8B%9B%E5%BE%85%E3%81%99%E3%82%8B#u25307u24453u12522u12531u12463u12434u20849u26377u12377u12427
> フリープラン、プロプラン、ビジネスプラスプランでは、招待を送信できる権限を持つメンバーが、招待リンクを共有することもできます。招待リンクを使用できるのは 1 つにつき最大 400 名となっています。

と記載があるので、メンテフリーとまではいかないようです。

参考までに、ruby-jpはこの方法で作成したURLを使っているようでした。 https://github.com/ruby-jp/ruby-jp.github.io/pull/31

**Comment by syohex** [comment]
expiration dayって出てきたから有効期限があるのかと思ったけど, 無期限もあるようなのでそれで良さそうですね
